Repository Mintbase/near-ca, pull requests merged in 2024-10, with the labels that each got.

#125 Fix Recent Upgrades
  package.json
  tests/unit/mpcContract.test.ts
  yarn.lock
Labels: dependencies, Review effort [1-5]: 1, Other

#126 Arbitrum is not a Testnet
  src/constants.ts
  tests/unit/utils.signature.test.ts
Labels: Review effort [1-5]: 1, bug_fix

#127 Base 64 Token & Network Icons
  src/constants.ts
  src/network.ts
Labels: enhancement, Review effort [1-5]: 3
