Repository Mintbase/near-ca, pull requests merged in 2024-05, with the labels that each got.

#34 Wallet Connect Session Request Handler
  package.json
  src/chains/ethereum.ts
  src/wallet-connect/handlers.ts
  tests/wc.handlers.test.ts
  yarn.lock
Labels: alpha

#61 Update Package Dependencies
  package.json
  yarn.lock
Labels: maintenance

#56 Add Examples Readme
  README.md
  examples/README.md
Labels: ethberlin2024

#57 docs: ETH Account Funding Guide
  README.md
  examples/getEthAddress.ts
Labels: ethberlin2024
