Repository Mintbase/near-ca, pull requests merged in 2024-06, with the labels that each got.

#50 Types: Improve Interface
  src/chains/ethereum.ts
  src/types/types.ts
Labels: UX

#67 Yarn Update
  package.json
  tests/unit/utils.signature.test.ts
  tests/unit/utils.transaction.test.ts
  tests/unit/wc.handlers.test.ts
  yarn.lock
Labels: easy

#60 Add instructions to get your near account id and private key
  README.md
Labels: ethberlin2024
